apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: realtime-dev
nameSuffix: -dev
resources:
- ../../bases/realtimeapp
- namespace.yaml
transformers:
- labels.yaml
replicas:
- count: 1
  name: realtime
images:
- name: gbaeke/flux-rt
  newTag: sha-11e921f
